// One-off generator: precomputes the dotted world map and the projected
// x/y coordinates for our destination pins + hub, so the React component can
// render everything perfectly aligned.
//
// Run with:  node scripts/generate-map.mjs
// Output:    src/components/mapData.ts

import DottedMapModule from "dotted-map";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const DottedMap = DottedMapModule.default || DottedMapModule;
const __dirname = path.dirname(fileURLToPath(import.meta.url));

const MAP_OPTS = { height: 60, grid: "diagonal" };

const map = new DottedMap(MAP_OPTS);

// Destinations (real lat/lng) + hub
const places = {
  hub: { lat: 20.5937, lng: 78.9629 }, // India (QCS crossroads hub)
  CA: { lat: 56.1304, lng: -106.3468 }, // Canada
  US: { lat: 39.8283, lng: -98.5795 }, // USA
  UK: { lat: 54.0, lng: -2.0 }, // United Kingdom
  AU: { lat: -25.2744, lng: 133.7751 }, // Australia
  NZ: { lat: -41.0, lng: 174.0 }, // New Zealand
  DE: { lat: 51.1657, lng: 10.4515 }, // Germany
  IE: { lat: 53.4129, lng: -8.2439 }, // Ireland
  FR: { lat: 46.2276, lng: 2.2137 }, // France
  NL: { lat: 52.1326, lng: 5.2913 }, // Netherlands
  IT: { lat: 41.8719, lng: 12.5674 }, // Italy
  ES: { lat: 40.4637, lng: -3.7492 }, // Spain
  SE: { lat: 60.1282, lng: 18.6435 }, // Sweden
  CH: { lat: 46.8182, lng: 8.2275 }, // Switzerland
  SG: { lat: 1.3521, lng: 103.8198 }, // Singapore
};

// Add pins and capture their projected x/y (grid units)
const pinCoords = {};
for (const [code, coord] of Object.entries(places)) {
  const pin = map.addPin({
    lat: coord.lat,
    lng: coord.lng,
    svgOptions: { radius: 0 },
  });
  pinCoords[code] = { x: pin.x, y: pin.y };
}

// Get the full SVG (so we can read the exact viewBox), then extract the inner
// <circle> markup only — we'll render our own <svg> wrapper in React.
const fullSvg = map.getSVG({
  radius: 0.35,
  color: "#ffffff",
  shape: "circle",
  backgroundColor: "transparent",
});

const viewBoxMatch = fullSvg.match(/viewBox="([^"]+)"/);
const viewBox = viewBoxMatch ? viewBoxMatch[1] : "0 0 119 60";
const [, , vbW, vbH] = viewBox.split(" ").map(Number);

// Inner content = everything between the outer <svg ...> and </svg>
const inner = fullSvg
  .replace(/^[\s\S]*?<svg[^>]*>/, "")
  .replace(/<\/svg>\s*$/, "")
  .trim();

const out = `// AUTO-GENERATED by scripts/generate-map.mjs — do not edit by hand.
/* eslint-disable */
// Precomputed dotted world map (inner <circle> dots) + projected pin coords.

export const VIEWBOX = { width: ${vbW}, height: ${vbH} };

export const PIN_COORDS: Record<string, { x: number; y: number }> = ${JSON.stringify(
  pinCoords,
  null,
  2
)};

export const MAP_DOTS = ${JSON.stringify(inner)};
`;

const outPath = path.join(__dirname, "..", "src", "components", "mapData.ts");
fs.writeFileSync(outPath, out);
console.log("Wrote", outPath);
console.log("viewBox", viewBox, "->", { vbW, vbH });
console.log("pins", pinCoords);
console.log("dots markup length", inner.length);
